import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import SummaryStep from './SummaryStep.jsx'
import { buildPipelineChangeSignature } from '../../shared/services/pipelineChangeDetection.js'

const mockWizardState = {
  metadata: {
    entityName: 'product',
    productSource: 'ERP',
    productType: 'Catalog',
    location: '',
    environment: 'production',
    team: 'data-platform',
  },
  source: {
    sourceType: 'kafka',
    kafkaTopic: 'catalog-topic',
    kafkaOffset: 'earliest',
    kafkaKeys: 'sku-key, inventory-key',
    format: 'JSON',
    streamingContinuity: 'continuous',
    recordsPerDay: 'millions',
  },
  upload: {
    done: true,
    schema: [
      { id: 'sku', name: 'sku', path: 'sku', type: 'string', nullable: false },
    ],
  },
  targetSchema: [
    { id: 'sku', name: 'sku', path: 'sku', type: 'string', required: true },
  ],
  mappings: [
    {
      src: 'sku',
      tgt: 'sku',
      transformer: 'none',
      extraInputs: [
        { field: 'skuVariant' },
      ],
    },
  ],
  filters: [],
  sink: {
    sinkType: 'kafka',
    sinkKafkaTopic: 'catalog-sink',
    sinkKafkaAdditionalProperties: [],
  },
  originalDraftYaml: '',
  originalDraftSignature: '',
}

const mockActions = {
  setNavigationMode: vi.fn(),
  goTo: vi.fn(),
}

const mockSaveDraftConfiguration = vi.fn(() => Promise.resolve({ success: true }))
const mockFetchDeploymentSteps = vi.fn(() => Promise.resolve([{ id: 'validate', label: 'Validate' }]))
const mockDeployFromYaml = vi.fn(() => Promise.resolve({ success: true, deploymentId: 'dep-1' }))
const mockSubscribeToDeploymentProgress = vi.fn(() => vi.fn())

vi.mock('../../shared/store/wizardStore.jsx', () => ({
  useWizard: () => ({
    state: mockWizardState,
    actions: mockActions,
  }),
}))

vi.mock('../../shared/store/configContext.jsx', () => ({
  useConfig: () => ({
    transformers: [],
  }),
}))

vi.mock('../../shared/hooks/useDeploymentProgress.js', () => ({
  useDeploymentProgress: () => ({
    isOpen: false,
    steps: [],
    currentStepIndex: 0,
    isComplete: false,
    isError: false,
    errorMessage: '',
    startDeployment: vi.fn(),
    reset: vi.fn(),
  }),
}))

vi.mock('../../shared/services/configService.js', () => ({
  MOCK_FILTER_OPERATORS: [],
  saveDraftConfiguration: (...args) => mockSaveDraftConfiguration(...args),
}))

vi.mock('../../shared/services/deploymentsService.js', () => ({
  fetchDeploymentSteps: (...args) => mockFetchDeploymentSteps(...args),
  deployFromYaml: (...args) => mockDeployFromYaml(...args),
  subscribeToDeploymentProgress: (...args) => mockSubscribeToDeploymentProgress(...args),
}))

describe('SummaryStep save draft behavior', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    mockWizardState.originalDraftYaml = ''
    mockWizardState.originalDraftSignature = ''
    mockWizardState.metadata.location = ''
    mockWizardState.source.format = 'JSON'
    mockWizardState.source.csvDelimiter = undefined
    mockWizardState.source.rowDelimiter = ''
    mockWizardState.source.jsonSplit = ''
    mockWizardState.source.kafkaOffset = 'earliest'
    mockWizardState.source.kafkaKeys = 'sku-key, inventory-key'
    mockActions.setNavigationMode.mockReset()
    mockActions.goTo.mockReset()
    mockSaveDraftConfiguration.mockClear()
    mockFetchDeploymentSteps.mockClear()
    mockDeployFromYaml.mockClear()
    mockSubscribeToDeploymentProgress.mockClear()
  })

  afterEach(() => {
    vi.runOnlyPendingTimers()
    vi.useRealTimers()
  })

  it('saves the draft and navigates to management after the success popup closes', async () => {
    render(<SummaryStep />)

    await act(async () => {
      fireEvent.click(screen.getByRole('button', { name: /save draft/i }))
      await Promise.resolve()
    })

    expect(mockSaveDraftConfiguration).toHaveBeenCalledTimes(1)

    expect(screen.getByText('Draft Saved')).toBeInTheDocument()

    await act(async () => {
      vi.advanceTimersByTime(1800)
      await Promise.resolve()
    })

    expect(mockActions.setNavigationMode).toHaveBeenCalledWith('etl-management')
  })

  it('shows a no-change popup and skips deployment when the edited YAML is unchanged', async () => {
    mockWizardState.metadata.location = 'OFFICE'
    mockWizardState.originalDraftYaml = `# Generated by ETL Pipeline Studio
metadata:
  id: etl-existing
  genomeEntity: product
  location: "OFFICE"
  productSource: ERP
  productType: Catalog
  environment: production
  owner: data-platform
  dataStreamInfo:
    streaming_continuity: continuous
    avg_records_amount: millions

source:
  kafka:
    topic: catalog-topic
    offset: earliest
    filter: "sku-key, inventory-key"
input:
  convert:
    mapping:
      - name: sku
        type: string
general:
  format: JSON

output:
  mapping:
    - inName: sku
      outName: sku
      sendToSaknay: true
  filters: []

sink:
  saknay: true
  saknay_topic: auto
  type: kafka
  topic: catalog-sink`
    mockWizardState.originalDraftSignature = buildPipelineChangeSignature(mockWizardState)

    render(<SummaryStep />)

    expect(screen.getByRole('button', { name: /save & deploy/i })).toHaveTextContent('🚀 Save & Deploy')

    await act(async () => {
      fireEvent.click(screen.getByRole('button', { name: /save & deploy/i }))
      await Promise.resolve()
    })

    expect(screen.getByText('No Changes Detected')).toBeInTheDocument()
    expect(screen.getByText('No changes were detected compared to the existing pipeline YAML. The system will not deploy anything.')).toBeInTheDocument()
    expect(mockFetchDeploymentSteps).not.toHaveBeenCalled()
    expect(mockDeployFromYaml).not.toHaveBeenCalled()

    await act(async () => {
      fireEvent.click(screen.getByRole('button', { name: 'OK' }))
      await Promise.resolve()
    })

    expect(mockActions.setNavigationMode).toHaveBeenCalledWith('etl-management')
  })

  it('blocks deployment when kafka offset is missing', async () => {
    mockWizardState.metadata.location = 'OFFICE'
    mockWizardState.source.kafkaOffset = ''

    render(<SummaryStep />)

    await act(async () => {
      fireEvent.click(screen.getByRole('button', { name: /save & deploy/i }))
      await Promise.resolve()
    })

    expect(screen.getByText('Source Configuration Incomplete')).toBeInTheDocument()
    expect(screen.getByText('Please configure your Kafka source settings (type, topic, and offset) and try again.')).toBeInTheDocument()
    expect(mockFetchDeploymentSteps).not.toHaveBeenCalled()
    expect(mockDeployFromYaml).not.toHaveBeenCalled()
  })

  it('sends deploy request params and configurationYaml when saving and deploying', async () => {
    mockWizardState.metadata.location = 'OFFICE'
    mockWizardState.source.kafkaOffset = 'earliest'
    mockWizardState.source.kafkaKeys = 'sku-key, inventory-key'

    render(<SummaryStep />)

    await act(async () => {
      fireEvent.click(screen.getByRole('button', { name: /save & deploy/i }))
      await Promise.resolve()
    })

    expect(mockFetchDeploymentSteps).toHaveBeenCalledTimes(1)
    expect(mockDeployFromYaml).toHaveBeenCalledWith(expect.objectContaining({
      productType: 'Catalog',
      source: 'ERP',
      team: 'data-platform',
      environment: 'production',
      isDeploy: true,
      configurationYaml: expect.stringContaining('productType: Catalog'),
    }))
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('genomeEntity: product')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('\n  entity:')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('location: "OFFICE"')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('source:\n  kafka:\n    topic: catalog-topic')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('offset: earliest')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('filter: "sku-key, inventory-key"')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('input:\n  convert:\n    mapping:\n      - name: sku')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('source:\n  type: kafka')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('source:\n  format: JSON')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('keyFilter:')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('general:\n  format: JSON')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('inputFormat:')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('outputFormat:')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('additionalInputs:')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('additional_inputs:')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('streamingContinuity: continuous')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).toContain('avgRecordsAmount: millions')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('streaming_continuity:')
    expect(mockDeployFromYaml.mock.calls[0][0].configurationYaml).not.toContain('avg_records_amount:')
    expect(mockSubscribeToDeploymentProgress).toHaveBeenCalledWith('dep-1', expect.any(Object))
  })

  it('serializes CSV row delimiter under general.split.delimiter', async () => {
    mockWizardState.source.format = 'CSV'
    mockWizardState.source.csvDelimiter = ';'
    mockWizardState.source.rowDelimiter = '\\r\\n'

    render(<SummaryStep />)

    await act(async () => {
      fireEvent.click(screen.getByRole('button', { name: /save & deploy/i }))
      await Promise.resolve()
    })

    const yaml = mockDeployFromYaml.mock.calls[0][0].configurationYaml
    expect(yaml).toContain('general:\n  format: CSV')
    expect(yaml).toContain('input:\n  delimited:\n    columnDelimiter: ";"\n    mapping:\n      - name: sku')
    expect(yaml).toContain('split:')
    expect(yaml).toContain('delimiter: "\\\\r\\\\n"')
  })

  it('serializes JSON split key under input.convert.splitByPath', async () => {
    mockWizardState.source.format = 'JSON'
    mockWizardState.source.jsonSplit = '$.items'

    render(<SummaryStep />)

    await act(async () => {
      fireEvent.click(screen.getByRole('button', { name: /save & deploy/i }))
      await Promise.resolve()
    })

    const yaml = mockDeployFromYaml.mock.calls[0][0].configurationYaml
    expect(yaml).toContain('input:\n  convert:\n    splitByPath: "$.items"\n    mapping:\n      - name: sku')
    expect(yaml).not.toContain('split_key:')
  })
})