import { useState } from 'react'
import { useWizard } from "../../shared/store/wizardStore";
import { Card, CardTitle, ValidationItem, Btn } from '../../shared/components/index.jsx'
import { SOURCE_TYPES } from '../../shared/types/index.js'

function FlinkFlow({ sourceType, mappings, filters, sink }) {
  const nodes = [
    { id: 'src',    label: 'Source',   sub: sourceType?.toUpperCase() || 'KAFKA',      color: '#4f6ef7', pl: 2 },
    { id: 'map',    label: 'Mapping',  sub: `${mappings.length} fields`,               color: '#22c55e', pl: 4 },
    { id: 'filter', label: 'Filter',   sub: `${filters.reduce((a, g) => a + g.rules.length, 0)} rules`, color: '#f59e0b', pl: 2 },
    { id: 'sink',   label: 'Sink',     sub: sink?.sinkType?.toUpperCase() || 'KAFKA',  color: '#ec4899', pl: 2 },
  ]
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 0, flexWrap: 'wrap', justifyContent: 'center', padding: '10px 0' }}>
      {nodes.map((n, i) => (
        <div key={n.id} style={{ display: 'flex', alignItems: 'center' }}>
          <div style={{
            background: `${n.color}22`, border: `2px solid ${n.color}`,
            borderRadius: 10, padding: '12px 20px', textAlign: 'center', minWidth: 100,
          }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: n.color }}>{n.label}</div>
            <div style={{ fontSize: 10, color: 'var(--muted)', marginTop: 2, fontFamily: 'var(--mono)' }}>{n.sub}</div>
            <div style={{ fontSize: 9, color: 'var(--muted)', marginTop: 4 }}>P={n.pl}</div>
          </div>
          {i < nodes.length - 1 && (
            <div style={{ display: 'flex', alignItems: 'center', margin: '0 4px' }}>
              <div style={{ width: 20, height: 2, background: 'var(--border)' }} />
              <div style={{ width: 0, height: 0, borderTop: '5px solid transparent', borderBottom: '5px solid transparent', borderLeft: '8px solid var(--border)' }} />
            </div>
          )}
        </div>
      ))}
    </div>
  )
}

function YamlPreview({ state }) {
  const yaml = `# Generated by ETL Pipeline Studio
id: etl-${Math.random().toString(36).slice(2, 9)}
version: ${state.metadata.schemaVersion}
entity: ${state.metadata.entityName}
environment: ${state.metadata.environment}
team: ${state.metadata.team}

source:
  type: ${state.source.sourceType}
  format: ${state.source.format}
  bootstrap: ${state.source.kafkaBootstrap || 'N/A'}
  topic: ${state.source.kafkaTopic || 'N/A'}

mappings:
${state.mappings.map(m => `  - src: ${m.src}\n    tgt: ${m.tgt}${m.warn ? '\n    cast: true' : ''}`).join('\n')}

filters: ${state.filters.reduce((a, g) => a + g.rules.length, 0)} rules

sink:
  type: ${state.sink.sinkType}
  topic: ${state.sink.sinkKafkaTopic || state.sink.sinkFilePath || 'N/A'}
`
  return (
    <pre style={{
      fontFamily: 'var(--mono)', fontSize: 12, lineHeight: 1.75,
      color: '#a3b4cd', background: '#0d1117', borderRadius: 8,
      padding: '14px 18px', overflowX: 'auto', margin: 0,
    }}>
      {yaml.split('\n').map((line, i) => {
        const isComment   = line.startsWith('#')
        const isKey       = /^[a-z_]+:/.test(line.trim()) && !line.startsWith('  ')
        const isSubKey    = /^\s+[a-z_]+:/.test(line) && !line.includes('  - ')
        const isValue     = line.includes(': ') && !isKey
        return (
          <span key={i} style={{
            color: isComment ? '#586e75' : isKey ? '#d0e0ff' : isSubKey ? '#a3b4cd' : isValue ? '#7dd3fc' : '#a3b4cd',
            display: 'block',
            fontWeight: isKey ? 600 : 400,
          }}>
            {line}
          </span>
        )
      })}
    </pre>
  )
}

export default function SummaryStep() {
  const { state } = useWizard()
  const [submitted, setSubmitted] = useState(false)
  const [copying, setCopying] = useState(false)
  const srcMeta = SOURCE_TYPES.find(t => t.id === state.source.sourceType)
  const reqMapped = state.mappings.filter(m => ['name', 'unitPrice'].includes(m.tgt)).length

  const validations = [
    { type: reqMapped >= 2 ? 'ok' : 'err',  text: `Required fields mapped (${reqMapped}/2)` },
    { type: state.mappings.length > 0 ? 'ok' : 'warn', text: `${state.mappings.length} field mapping(s) defined` },
    { type: state.source.kafkaTopic ? 'ok' : 'warn', text: `Source configured: ${srcMeta?.name || 'unknown'}` },
    { type: state.metadata.productSource ? 'ok' : 'err', text: `Metadata: product source "${state.metadata.productSource}"` },
    { type: state.filters.length > 0 ? 'ok' : 'warn', text: `${state.filters.reduce((a, g) => a + g.rules.length, 0)} filter rule(s) active` },
    { type: state.sink.sinkType ? 'ok' : 'err', text: `Sink configured: ${state.sink.sinkType || 'none'}` },
  ]

  if (submitted) {
    const pipelineId = `ETL-${Date.now().toString(36).toUpperCase()}`
    return (
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: 40, textAlign: 'center', animation: 'fadeIn .4s ease' }}>
        <div style={{ fontSize: 64, marginBottom: 20 }}>🎉</div>
        <h2 style={{ fontSize: 26, fontWeight: 800, marginBottom: 10, background: 'linear-gradient(135deg,#4f6ef7,#7c3aed)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
          Pipeline Created!
        </h2>
        <p style={{ color: 'var(--muted)', marginBottom: 28, maxWidth: 440 }}>
          Your ETL pipeline has been registered and is ready for deployment.
        </p>
        <Card style={{ width: '100%', maxWidth: 460, textAlign: 'left' }} p="18px 22px">
          {[
            ['Pipeline ID', pipelineId],
            ['Entity',      `${state.metadata.entityName} ${state.metadata.schemaVersion}`],
            ['Mappings',    state.mappings.length],
            ['Environment', state.metadata.environment],
          ].map(([k, v]) => (
            <div key={k} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px solid var(--border)', fontSize: 13 }}>
              <span style={{ color: 'var(--muted)' }}>{k}</span>
              <span style={{ fontWeight: 600, fontFamily: 'var(--mono)', color: 'var(--accent)' }}>{v}</span>
            </div>
          ))}
        </Card>
        <div style={{ display: 'flex', gap: 12, marginTop: 24 }}>
          <Btn v="secondary">View in Registry</Btn>
          <Btn v="primary" onClick={() => setSubmitted(false)}>Create Another</Btn>
        </div>
      </div>
    )
  }

  return (
    <div style={{ flex: 1, overflowY: 'auto', padding: '24px 30px' }}>
      {/* Stats row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5,1fr)', gap: 14, marginBottom: 20 }}>
        {[
          { icon: '🏷️', label: 'Entity',   value: `${state.metadata.entityName} ${state.metadata.schemaVersion}` },
          { icon: '🔌', label: 'Source',   value: srcMeta?.name || '—' },
          { icon: '↔',  label: 'Mappings', value: state.mappings.length },
          { icon: '⚙',  label: 'Filters',  value: state.filters.reduce((a, g) => a + g.rules.length, 0) },
          { icon: '🔀', label: 'Sink',     value: (state.sink.sinkType || '—').toUpperCase() },
        ].map(s => (
          <div key={s.label} style={{
            background: 'var(--surf)', border: '1px solid var(--border)',
            borderRadius: 'var(--radius)', padding: '14px 18px', textAlign: 'center',
          }}>
            <div style={{ fontSize: 22, marginBottom: 6 }}>{s.icon}</div>
            <div style={{ fontSize: 11, color: 'var(--muted)', marginBottom: 4 }}>{s.label}</div>
            <div style={{ fontSize: 15, fontWeight: 700, fontFamily: 'var(--mono)', color: 'var(--accent)' }}>{s.value}</div>
          </div>
        ))}
      </div>

      {/* Flink flow */}
      <Card>
        <CardTitle>⚡ Flink Pipeline Flow</CardTitle>
        <FlinkFlow sourceType={state.source.sourceType} mappings={state.mappings} filters={state.filters} sink={state.sink} />
      </Card>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 }}>
        {/* Validation */}
        <Card>
          <CardTitle>✅ Validation Checklist</CardTitle>
          {validations.map((v, i) => (
            <ValidationItem key={i} type={v.type}>{v.text}</ValidationItem>
          ))}
        </Card>

        {/* YAML / JSON Quick edit */}
        <Card>
          <CardTitle>
            🔀 Quick Edit
          </CardTitle>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {['Metadata', 'Source Config', 'Field Mapping', 'Filters', 'Sink Config'].map((label, i) => (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '7px 0', borderBottom: '1px solid var(--border)' }}>
                <span style={{ fontSize: 13 }}>{label}</span>
                <Btn sm v="ghost">✏ Edit</Btn>
              </div>
            ))}
          </div>
        </Card>
      </div>

      {/* YAML Preview */}
      <Card>
        <CardTitle>
          📄 YAML Preview
          <Btn sm v="ghost" onClick={() => { setCopying(true); setTimeout(() => setCopying(false), 1500) }}
            style={{ marginLeft: 'auto' }}>
            {copying ? '✓ Copied' : '📋 Copy YAML'}
          </Btn>
        </CardTitle>
        <YamlPreview state={state} />
      </Card>

      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 12, marginTop: 8 }}>
        <Btn v="secondary">💾 Save Draft</Btn>
        <Btn v="success" onClick={() => setSubmitted(true)}>✓ Create ETL Pipeline</Btn>
      </div>
    </div>
  )
}
